fs            = require 'fs'
{print}       = require 'util'
{spawn, exec} = require 'child_process'

log = (data) -> print data.toString()

task 'build', 'Build and watch the CoffeeScript source files', ->
  coffee = spawn 'coffee', ['-cwb', '-o', '.', '.']
  coffee.stdout.on 'data', log

task 'doc', 'Regenerate Documentation', ->
  docco = spawn 'docco', ['../']
  docco.stdout.on 'data', log